name: Build and Release Linux

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write  # 这行很重要，明确授予写入内容的权限

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    
    - name: Build
      run: go build -v -o tong-linux .
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./tong-linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}