name: Build and Release Mac

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write  # 这行很重要，明确授予写入内容的权限

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    
    - name: Verify Go installation
      run: |
        go version
        echo $GOROOT
        echo $PATH
    
    - name: Set Go environment
      run: |
        echo "GOROOT=$(go env GOROOT)" >> $GITHUB_ENV
        echo "$(go env GOROOT)/bin" >> $GITHUB_PATH
    
    - name: Build
      run: |
        echo $GOROOT
        echo $PATH
        go build -v -o tong-mac .
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./tong-mac
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}